"""D4 - loads: device types, control kinds, store models, the write gate (HLD §6.4).

The public API D4 §3 names. Turning "a device in Home Assistant" into a `Load`
the allocator can reason about, and turning a `Grant` into the fewest, safest
writes that achieve it - all of it pure (INV-2): every device write leaves as a
`Command` on an `ApplyResult` and is performed by `writegate.py`, the
only caller of `hass.services` (INV-3, INV-20).

Importing this package registers every device type that ships, so
`device_types.keys()` answers what a subentry may be.

WP0.5 builds the core: the two types the reference house runs on (`ev`,
`floor_heating`), the four control kinds, the store models, the target profiles,
the questionnaire framework and the gate decision. The other six types
(D4 §6.3–6.8), the `sg_ready` kind, the device profiles
(`providers/profiles/`) and the gate's executor are phases 2, 3 and 5.
"""

from ..model import ComfortState, Demand, Grant, Mode, Urgency
from .base import (
    Action,
    ActionReason,
    ApplyResult,
    Command,
    ControlKind,
    Desired,
    GateConfig,
    GateState,
    Health,
    Hold,
    KindCtx,
    Learned,
    Load,
    LoadConfig,
    LoadCtx,
    LoadState,
    Observation,
    Reads,
    ReasonParams,
    Role,
    RoleRead,
    SessionDone,
    Transition,
    Transport,
    TransportBudget,
    TypeLogic,
    Value,
    Write,
    effective_mode,
    expire_force,
    gate_config,
    transition,
)
from .gate import (
    TRANSIENT_GRACE_S,
    TRANSPORT_LIMIT_PER_MIN,
    UNHEALTHY_AT,
    Decision,
    decide,
    same,
)
from .questionnaire import (
    AnswerError,
    Answers,
    Derived,
    Explanation,
    Option,
    QCtx,
    Question,
    QuestionKind,
    Questionnaire,
    explain,
    materialise,
    rederive,
)
from .registry import CONTROL_KINDS, build_load, control_kinds, device_types
from .stores import (
    DEFAULT_COP_CURVES,
    CopCurve,
    EnergyStore,
    RoomStore,
    SlabStore,
    StoreCtx,
    StoreModel,
    TankStore,
)
from .targets import (
    CalendarEvent,
    ConstantSchedule,
    HaScheduleEntity,
    LocalWindow,
    PresenceMode,
    ScheduleSource,
    TargetProfile,
    WeeklyRow,
    WeeklyTable,
)

__all__ = [
    "CONTROL_KINDS",
    "DEFAULT_COP_CURVES",
    "TRANSIENT_GRACE_S",
    "TRANSPORT_LIMIT_PER_MIN",
    "UNHEALTHY_AT",
    "Action",
    "ActionReason",
    "AnswerError",
    "Answers",
    "ApplyResult",
    "CalendarEvent",
    "ComfortState",
    "Command",
    "ConstantSchedule",
    "ControlKind",
    "CopCurve",
    "Decision",
    "Demand",
    "Derived",
    "Desired",
    "EnergyStore",
    "Explanation",
    "GateConfig",
    "GateState",
    "Grant",
    "HaScheduleEntity",
    "Health",
    "Hold",
    "KindCtx",
    "Learned",
    "Load",
    "LoadConfig",
    "LoadCtx",
    "LoadState",
    "LocalWindow",
    "Mode",
    "Observation",
    "Option",
    "PresenceMode",
    "QCtx",
    "Question",
    "QuestionKind",
    "Questionnaire",
    "Reads",
    "ReasonParams",
    "Role",
    "RoleRead",
    "RoomStore",
    "ScheduleSource",
    "SessionDone",
    "SlabStore",
    "StoreCtx",
    "StoreModel",
    "TankStore",
    "TargetProfile",
    "Transition",
    "Transport",
    "TransportBudget",
    "TypeLogic",
    "Urgency",
    "Value",
    "WeeklyRow",
    "WeeklyTable",
    "Write",
    "build_load",
    "control_kinds",
    "decide",
    "device_types",
    "effective_mode",
    "expire_force",
    "explain",
    "gate_config",
    "materialise",
    "rederive",
    "same",
    "transition",
]
