"""vulture's reviewed false positives (D9 §5.8, CONTRIBUTING.md).

Every name here was checked by hand and is alive in a way vulture
cannot see: an enum member looked up by value, a dataclass field read by
`asdict`/`getattr` or kept in stored state, a test method dispatched by
`getattr`, a Protocol that documents a shape, `savings_guard.py`'s optional
helpers (D12 F10). What Home Assistant or a registry calls by name is in
`[tool.vulture]` instead. Add a line only for a name you verified is alive;
dead code is deleted, not listed. Regenerate the lines with
`uv run vulture --make-whitelist` and keep this header.
"""

# ruff: noqa
last_slot_utc  # unused variable (custom_components/powerplan/core/accounting/close.py:196)
_.last_slot_utc  # unused attribute (custom_components/powerplan/core/accounting/close.py:358)
_.calib_cf_kwh  # unused attribute (custom_components/powerplan/core/accounting/close.py:596)
calib_cf_kwh  # unused variable (custom_components/powerplan/core/accounting/ledger.py:143)
e_budget_kwh  # unused variable (custom_components/powerplan/core/allocation/budget.py:194)
scope_id  # unused variable (custom_components/powerplan/core/allocation/constraints/base.py:62)
trim_freed_w  # unused variable (custom_components/powerplan/core/allocation/report.py:159)
severe  # unused variable (custom_components/powerplan/core/engine.py:455)
cap_now_w  # unused variable (custom_components/powerplan/core/engine.py:562)
lifetime_cost  # unused variable (custom_components/powerplan/core/engine.py:692)
lifetime_savings  # unused variable (custom_components/powerplan/core/engine.py:693)
unhealthy_loads  # unused variable (custom_components/powerplan/core/engine.py:724)
failed_loads  # unused variable (custom_components/powerplan/core/engine.py:725)
degraded_meter  # unused variable (custom_components/powerplan/core/engine.py:728)
prices_stale  # unused variable (custom_components/powerplan/core/engine.py:729)
forecasts_available  # unused variable (custom_components/powerplan/core/engine.py:730)
boundary_tick  # unused variable (custom_components/powerplan/core/engine.py:733)
last_plan_at  # unused variable (custom_components/powerplan/core/engine.py:779)
slot_start  # unused variable (custom_components/powerplan/core/engine.py:912)
OCCUPANCY  # unused variable (custom_components/powerplan/core/forecasts/model.py:69)
start_at  # unused variable (custom_components/powerplan/core/loads/base.py:202)
finished_at  # unused variable (custom_components/powerplan/core/loads/base.py:204)
substitutable  # unused variable (custom_components/powerplan/core/loads/base.py:270)
label_key  # unused variable (custom_components/powerplan/core/loads/questionnaire.py:101)
help_key  # unused variable (custom_components/powerplan/core/loads/questionnaire.py:121)
frequency_hz  # unused variable (custom_components/powerplan/core/metering/profile.py:81)
t_elapsed_h  # unused variable (custom_components/powerplan/core/metering/window.py:193)
DISTRICT_HEAT  # unused variable (custom_components/powerplan/core/model.py:79)
OIL  # unused variable (custom_components/powerplan/core/model.py:80)
PELLETS  # unused variable (custom_components/powerplan/core/model.py:81)
IMPLAUSIBLE  # unused variable (custom_components/powerplan/core/model.py:183)
FORECAST  # unused variable (custom_components/powerplan/core/strategies/adoption.py:205)
level_name  # unused variable (custom_components/powerplan/core/tariffs/evaluator.py:192)
raw_kw  # unused variable (custom_components/powerplan/core/tariffs/evaluator.py:260)
DAY_MIN  # unused variable (custom_components/powerplan/core/tariffs/model.py:52)
history_policy  # unused variable (custom_components/powerplan/core/tariffs/model.py:324)
T5  # unused variable (custom_components/powerplan/core/tariffs/sources/base.py:58)
has_battery  # unused variable (custom_components/powerplan/dashboard/site_layout.py:67)
option_names  # unused variable (custom_components/powerplan/providers/profiles/base.py:752)
flat_reference_cost  # unused function (custom_components/powerplan/savings_guard.py:55)
pytestmark  # unused variable (tests/backtest/test_house_recorder.py:38)
_._floor_heating  # unused method (tests/e2e/fake_house.py:317)
_._water_heater  # unused method (tests/e2e/fake_house.py:387)
_._heat_pump  # unused method (tests/e2e/fake_house.py:410)
_._radiator  # unused method (tests/e2e/fake_house.py:439)
_._appliance_cycle  # unused method (tests/e2e/fake_house.py:461)
_._generic_switch  # unused method (tests/e2e/fake_house.py:477)
pytestmark  # unused variable (tests/e2e/test_e2e_day.py:78)
pytestmark  # unused variable (tests/e2e/test_observe_writes_nothing.py:55)
async_test_recorder  # unused variable (tests/flows/test_monetary_statistics.py:52)
async_test_recorder  # unused variable (tests/providers/meters/test_recorder.py:45)
FALL_BACK_QUARTERS  # unused variable (tests/providers/prices/test_entity_source.py:36)
_.linkname  # unused attribute (tests/providers/tariffs/test_fri_nettleie_fetcher.py:63)
async_test_recorder  # unused variable (tests/runtime/test_recorder_seed.py:83)
at_boundary_minus_one  # unused variable (tests/runtime/test_runtime.py:75)
at_boundary_minus_one  # unused variable (tests/runtime/test_runtime.py:164)
PHASE1  # unused variable (tests/scenarios/catalogue.py:524)
PHASE2  # unused variable (tests/scenarios/catalogue.py:525)
PHASE3  # unused variable (tests/scenarios/catalogue.py:526)
PHASE4  # unused variable (tests/scenarios/catalogue.py:533)
PHASE7  # unused variable (tests/scenarios/catalogue.py:749)
TWIN_END  # unused variable (tests/scenarios/catalogue.py:536)
OFFSET_S  # unused variable (tests/scenarios/runner.py:101)
reasons_sample  # unused variable (tests/scenarios/runner.py:215)
_.reasons_sample  # unused attribute (tests/scenarios/runner.py:881)
pytestmark  # unused variable (tests/scenarios/test_accounting.py:28)
pytestmark  # unused variable (tests/scenarios/test_phase0.py:27)
pytestmark  # unused variable (tests/scenarios/test_phase1.py:26)
pytestmark  # unused variable (tests/scenarios/test_phase2.py:28)
pytestmark  # unused variable (tests/scenarios/test_phase3.py:60)
pytestmark  # unused variable (tests/scenarios/test_phase4.py:47)
SimLoad  # unused class (tests/sim/base.py:196)
SimSource  # unused class (tests/sim/base.py:205)
COMFORT_MIN_C  # unused variable (tests/sim/tank.py:33)
SSB_DETACHED_ANNUAL_KWH  # unused variable (tests/sim/uncontrolled.py:56)
hass_config_dir  # unused variable (tests/surface/test_repairs.py:167)
BOLT  # unused variable (tools/brand/make_brand.py:34)
